name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Where to go?
        options:
          - london
          - berlin
          - budapest
          - someehere eles
        required: true
      message:
        description: What is your message?
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis?
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
